version: "3"
services:
  cqp-inspance:
    build:
      context: Dockerfile
    image: cqp-instance-img
    depends_on:
      - redis
    ports:
    - "8000:8000"
  redis:
    image: redis:alpine
    volumes:
      - "opt/redis:/etc/redis"
    command: redis-server /etc/redis/redis.conf